export type Article={slug:string;title:string;dek:string;description:string;publishedAt:string;readingMinutes:number;category:string;tags:string[];body:{heading?:string;paragraphs:string[]}[]};
export type MusicEntry={slug:string;title:string;eyebrow:string;description:string;themes:string[];story:string;youtubeUrl?:string};
export const articles:Article[]=[{slug:'why-rudranaada-exists',title:'Why RudraNāda Exists: A Home for Story, Sound and Meaning',dek:'RudraNāda begins with music, but the larger idea is to make India’s epic and devotional traditions easier to enter without flattening their complexity.',description:'An introduction to RudraNāda’s editorial approach to Indian epics, devotional traditions, music and source-aware storytelling.',publishedAt:'2026-09-21',readingMinutes:5,category:'RudraNāda',tags:['RudraNāda','Indian epics','devotional music'],body:[{paragraphs:['A song can open a door that an index cannot. A single line about Krishna, Shiva, Kali, Hanuman or Narasimha can send a listener toward a story, a verse, a philosophical question or a tradition carried for centuries.','RudraNāda is being built around that doorway. The aim is not to reduce large traditions to quick answers. It is to connect sound, story and source so curiosity has somewhere deeper to go.']},{heading:'Music is the beginning, not the boundary',paragraphs:['The RudraNāda YouTube channel is where many people will first meet the project. The website expands that experience with lyrics, meanings, narrative context, character guides, festival explainers and carefully researched articles.']},{heading:'Text, tradition and interpretation are not the same thing',paragraphs:['Indian epic and devotional traditions are layered. RudraNāda will try to label those layers rather than quietly blending them together. When sources disagree, the disagreement is part of the story.']}] }];

export const music:MusicEntry[]=[
{slug:'uth-parth',title:'Uth Parth',eyebrow:'Mahabharata · Krishna & Arjuna',description:'A RudraNāda composition from the battlefield world of the Mahabharata.',themes:['Krishna','Arjuna','Mahabharata','dharma'],story:'Explore the composition alongside the larger questions of duty, fear and action that frame Krishna and Arjuna’s battlefield dialogue.'},
{slug:'mahakali',title:'Mahakali',eyebrow:'Devi · Devotional',description:'A dark, meditative RudraNāda composition centered on Mahakali.',themes:['Mahakali','Devi','devotion'],story:'A musical entry point into the fierce and protective imagery associated with the Goddess.'},
{slug:'parashurama',title:'Parashurama',eyebrow:'Avatar · Epic',description:'A fierce RudraNāda composition inspired by Parashurama.',themes:['Parashurama','Vishnu','epic'],story:'A musical portrait of the warrior-sage, leading into the textual and regional traditions surrounding his story.'},
{slug:'krishnam-vande-jagadgurum',title:'Krishnam Vande Jagadgurum',eyebrow:'Krishna · Chant',description:'A RudraNāda chant celebrating Krishna as Jagadguru, teacher of the world.',themes:['Krishna','chant','Bhagavad Gita'],story:'A devotional chant opening toward Krishna as teacher, guide and divine presence.'}
];
export const deityHubs=[{slug:'krishna',name:'Krishna',description:'Stories, teachings, songs and symbols associated with Krishna.'},{slug:'shiva',name:'Shiva',description:'Devotional traditions, stories, symbols and RudraNāda music centered on Shiva.'},{slug:'devi',name:'Devi',description:'Kali, Durga and the many forms through which the Goddess is encountered.'},{slug:'hanuman',name:'Hanuman',description:'Bhakti, courage, service and the stories that shape Hanuman devotion.'},{slug:'narasimha',name:'Narasimha',description:'Fierceness, protection and the Prahlada narrative across text and tradition.'},{slug:'parashurama',name:'Parashurama',description:'The warrior-sage across epic, puranic and regional traditions.'}];
export const getArticle=(slug:string)=>articles.find(a=>a.slug===slug);
export const getMusic=(slug:string)=>music.find(m=>m.slug===slug);
